/*
Name : KAREL AMANULLAH ASHRAF

Title : Guess the Number

Description:

The fun and easy project "Guess the Number" is a short JAVA project that allows the user 
to guess the number generated by the computer and involves the following steps:

1. The system generates a random number from a given range say 1 to 100.
2. The User is prompted to enter their given number in a display dialogue box.
3. The computer then tells if the entered number matches the guesses number or it is 
	higher/lower than the generated number.
4. The game continuous under the user using the number.
5. Limiting the number of attempts. 
6. Adding more around. 
7. Displaying score. 
8. Giving point based on the number of attempt.*/




package techno;

import java.util.Random;
import java.util.Scanner;

public class Number {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        
        System.out.println("Guess the Number" + "\n" + "\n");
        
        System.out.println("Ahyye! Lets Play the Game" + "\n" + "\n");
        
        int totalScore = 0;
        int attempts = 0;
        int maxAttempts = 15;
        
        while(true) {
            Random random = new Random();
            
            int min = 1;
            int max = 100;
            int randomNumber = random.nextInt(max - min + 1) + min;
            
            String playAgain;
            
            System.out.println("Guess the number between 1 and 100" +"\n");
            
            int guess;
            do {
                System.out.print("Enter your guess: ");
                guess = scanner.nextInt();
                attempts++;
                
                if (guess < randomNumber) {
                    System.out.println("Too low! Try again.");
                } else if (guess > randomNumber) {
                    System.out.println("Too high! Try again.");
                } else {
                    System.out.println("Congratulations! You guessed the number.");
                    int score = maxAttempts - attempts + 1;
                    totalScore += score;
                    System.out.println("Score for this round: " + score);
                    System.out.println("Total Score: " + totalScore);
                }
            } while (guess != randomNumber && attempts < maxAttempts);
            
            if (attempts >= maxAttempts) {
                System.out.println("You've reached the maximum number of attempts.");
            }
            
            scanner.nextLine();
            
            while(true) {
                
                System.out.println( "\n" + "\n" + "Type 'YES/yes' or 'NO/no' ");
                playAgain = scanner.nextLine();
                
                if(playAgain.equals("yes") || playAgain.equals("YES") || playAgain.equals("no") || playAgain.equals("NO")) {
                    
                    System.out.println("\n" + "------------------------------------------------------------------"
                            + "--------------------------" +"\n");
                    
                    break;
                }
            }
            
            if(playAgain.equals("no") || playAgain.equals("NO")) {
                break;
            }
            
            attempts = 0;
        }
        
        System.out.println("Total Score: " + totalScore);
        
        scanner.close();
    }    
}

